---
- name: Install ZFS
  ansible.builtin.apt:
    name: zfsutils-linux
    update_cache: true
  notify: Reboot system

- name: Copy over ZFS key load service
  ansible.builtin.copy:
    src: files/zfs-load-key.service
    dest: /etc/systemd/system/zfs-load-key.service
    group: root
    owner: root
    mode: "0644"
  notify: Reboot system

- name: Enable ZFS key load service
  ansible.builtin.service:
    name: zfs-load-key
    enabled: true
  notify: Reboot system
