---
- name: Create/Update users
  ansible.builtin.user:
    name: "{{ item.name }}"
    comment: "{{ item.description }}"
    shell: "{{ item.shell }}"
    groups: "{{ user_groups + (item.additional_groups | default([])) }}"
    append: true
    state: present
    create_home: true
  loop: "{{ user_users }}"

- name: Set authorized keys for users
  ansible.posix.authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ item.ssh_pub_key }}"
    # exclusive: true
  loop: "{{ user_users }}"

- name: Configure bashrc
  ansible.builtin.lineinfile:
    path: "/home/{{ item.0.name }}/.bashrc"
    regex: "^(#)?{{ item.1 }}"
    line: "{{ item.1 }}"
    state: present
  with_nested:
    - "{{ user_users }}"
    - "{{ user_additional_bash_config | default([]) }}"
