---
- name: Configure Docker data dir
  ansible.builtin.include_tasks:
    file: configure_data_dir.yml

- name: Install Docker
  ansible.builtin.include_tasks:
    file: install_docker.yml

# - name: Configure Docker backups
#   ansible.builtin.include_tasks:
#     file: configure_backups.yml
#   when: docker_configure_backups
