- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Remove firewalld
  ansible.builtin.package:
    name: firewalld
    state: absent

- name: Remove snapd
  ansible.builtin.package:
    name: snapd
    state: absent
