- name: Add Debian backports repository
  ansible.builtin.apt_repository:
    repo: "deb http://deb.debian.org/debian {{ ansible_distribution_release }}-backports main contrib non-free"
    state: present
    update_cache: true

- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Remove firewalld
  ansible.builtin.package:
    name: firewalld
    state: absent

- name: Remove snapd
  ansible.builtin.package:
    name: snapd
    state: absent
