- name: Add Debian backports repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list
    line: "deb http://deb.debian.org/debian {{ ansible_facts['distribution_release'] }}-backports main contrib non-free"
    state: present
    create: false

- name: Install base packages
  ansible.builtin.package:
    name: "{{ base_packages }}"
    state: present

- name: Remove firewalld
  ansible.builtin.package:
    name: firewalld
    state: absent

- name: Remove snapd
  ansible.builtin.package:
    name: snapd
    state: absent
