- name: Bootstrap hosts with base config/packages
  hosts: all
  become: true
  roles:
    - user
    - base

- name: Install and configure Cockpit
  hosts: cockpit
  become: true
  roles:
    - cockpit
